### ISSUE TITLE
RuntimeError: cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by andrejsvet** [dirkclemens/pycul#1]
Dear Dirk
I am trying to migrate my home automation devices from Fhem to Home Assistant and one big issue is how to include FS20,FHT,ESA devices in HA software. Luckly I found your python script which would solve my problem and you really did an excellent job. Unfortunately after I ran the script (python3 cul2mqtt.py) and got the error (see below). It is possible to help because my skills in python programming are very low specially with asyncio.

Kind regards

Andrej

CUL serial port opened:
 SerialTransport(<_UnixSelectorEventLoop running=True closed=False debug=False>, <__main__.culRxTx object at 0x7f73bd7cbac0>, Serial<id=0x7f73bd7cb820, open=True>(port='/dev/ttyACM0', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))
cul2mqtt.py:132: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(0.3)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
cul2mqtt.py:135: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(0.3)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CUL init done.
starting loop
Traceback (most recent call last):
  File "cul2mqtt.py", line 702, in <module>
    loop.run_until_complete(culSAIO)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
RuntimeError: cannot reuse already awaited coroutine

**Comment by dirkclemens** [comment]
Andrej, I do not use this code any longer. My intention was indeed to switch from fhem to home assistant, too. 
But I still use fhem, so I did not maintain the code. It is deprecated since python 3. <4 or so. 
And as I am not a python expert, too, I cannot fix the code on short term.

**Comment by andrejsvet** [comment]
Thank you Dirk I appreciate for the quick rely. No problem I will try to dig in the code and correct the errors and may be I will be sucessfull...

Kind regards

Andrej
